### ISSUE TITLE
Agent Tags - Invisible 

### ISSUE THREAD

**Issue by r-ramsay** [crabchucker/zendesk-dark-theme#1]
Currently when tagging an agent with the theme enabled, it uses a light gray which isn't able to be seen on the background. 

![2018-05-18_12-57-02](https://user-images.githubusercontent.com/6723576/40213851-fd976aee-5a9a-11e8-8a52-70daa6dda826.png)

**Comment by crabchucker** [comment]
pushed latest commit to fix this
chrome app has been updated
